apiVersion: v1
kind: ConfigMap
metadata:
  name: government-api-config
  namespace: government-api-ns
data:
  DB_HOST: "postgres-svc.postgres-ns.svc.cluster.local"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME: "government_loan_db"
  PORT: "8081"