name: loanapp-project-ci
on:
 push:
    branches:
      - main
    pull_request:
      branches:
        - main

    permissions:
      contents: read
      packages: write


env:
  GO_VERSION: '1.21'

jobs:
  build-test-scan:
    name: Build, Test and Scan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component:
          - name: government-api
            path: './government_api/backend'
          - name: loanapp-validator
            path: './loan_validator_portal/backend'

    defaults:
      run:
        working-directory: ${{ matrix.component.path }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GO
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          cache-dependency-path: '**/go.sum'

      - name: Get dependencies
        run: |
           go mod download
           go mod verify

      - name: Build project
        run: go build -v main.go

      - name: Run tests
        run: go test -v main.go

      #Scan the source code using trivy
      - name: Scan source code
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'json'
          output: 'trivy-report-${{ matrix.component.name }}.json'
          severity: 'CRITICAL,HIGH,MEDIUM'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'

      # Generate SBOM using trivy
      - name: Generate SBOM
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'cyclonedx'
          output: 'sbom-${{ matrix.component.name }}.cdx.json'
          sbom: 'true'

        
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom-${{ matrix.component.name }}
          path: sbom-${{ matrix.component.name }}.cdx.json

      - name: Upload Trivy Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report-${{ matrix.component.name }}
          path: trivy-report-${{ matrix.component.name }}.json
  
  #Docker, build, scan, push and sign image
  docker-build-push:
    name: Docker image build, sign and  push
    needs: build-test-scan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component:
          - name: government-api
            path: './government_api/backend'
          - name: loanapp-validator
            path: './loan_validator_portal/backend'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: ${{ matrix.component.path }}
          file: ${{ matrix.component.path }}/Dockerfile
          push: false
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ matrix.component.name }}:v1
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker, dest=/tmp/${{ matrix.component.name }}.tar

      - name: Load image for Scanning and signing
        run: docker load -i /tmp/${{ matrix.component.name }}.tar

      - name: Verify docker images
        run: docker images
     
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          scan-ref: '${{ secrets.DOCKER_USERNAME }}/${{ matrix.component.name }}:v1'
          format: 'json'
          severity: 'CRITICAL,HIGH,MEDIUM'
          output: 'trivy-results-${{ matrix.component.name }}.json'
          exit-code: '0'
          ignore-unfixed: true

      - name: Generate SBOM
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          scan-ref: '${{ secrets.DOCKER_USERNAME }}/${{ matrix.component.name }}:v1'
          format: 'cyclonedx'
          output: 'sbom-${{ matrix.component.name }}.json'
      
      - name: Push Image to dockerhub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.component.name }}:v1

      - name: Upload trivy results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results-${{ matrix.component.name }}
          path: trivy-results-${{ matrix.component.name }}.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom-${{ matrix.component.name }}
          path: sbom-${{ matrix.component.name }}.json

      - name: Set up Cosign
        uses: sigstore/cosign-installer@main

      - name: Write Cosign Key
        env: 
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
        run: 'echo "${{ secrets.COSIGN_PRIVATE_KEY }}" > cosign.key'

      - name: sign Docker image
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }} 
        run: |
           cosign sign --key cosign.key ${{ secrets.DOCKER_USERNAME }}/${{ matrix.component.name }}:v1
