name: loanapp-project-ci
on:
 push:
    branches:
      - main
    pull_request:
      branches:
        - main

    permissions:
      contents: read

env:
  GO_VERSION: '1.21'

jobs:
  build-test-scan:
    name: Build, Test and Scan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component:
          - name: government-api
            path: './government_api/backend'
          - name: loanapp-validator
            path: './loan_validator_portal/backend'

    defaults:
      run:
        working-directory: ${{ matrix.component.path }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GO
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          cache-dependency-path: '**/go.sum'

      - name: Get dependencies
        run: |
           go mod download
           go mod verify

      - name: Build project
        run: go build -v main.go

      - name: Run tests
        run: go test -v main.go

      #Scan the source code using trivy
      - name: Install Trivy
        uses: aquasecurity/trivy-action@master
        with:
          version: latest
          scan-type: 'fs'
          scan-ref: '.'

      - name: Debug repository structure
        run: |
          echo "=== Repository Structure ==="
          pwd
          ls -la
          echo ""
          echo "=== Looking for Go projects ==="
          find . -name "go.mod" -type f | head -10
          echo ""
          echo "=== Looking for government_api ==="
          find . -type d -name "*government*" 2>/dev/null || echo "Not found"

      - name: Generate SBOM
        run: |
           trivy fs ./main.go \
             --format cyclonedx \
             --output sbom-${{ matrix.component.name }}.cdx.json


      - name: Scan source code
        run: |
          trivy fs ./main.go \
            --format json \
            --output trivy-report-${{ matrix.component.name }}.json \
            --ignore-unfixed \
            --pkg-types os, library

        
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom-${{ matrix.component.name }}
          path: sbom-${{ matrix.component.name }}.cdx.json

      - name: Upload Trivy Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report-${{ matrix.component.name }}
          path: trivy-report-${{ matrix.component.name }}.json

