name: loanapp-project-ci
on:
 push:
    branches:
      - main
    pull_request:
      branches:
        - main

    permissions:
      contents: read

env:
  GO_VERSION: '1.21'

jobs:
  docker-build-push:
    name: Docker image build, sign and  push
    #needs: build-test-scan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component:
          - name: government-api
            path: './government_api/backend'
          - name: loanapp-validator
            path: './loan_validator_portal/backend'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker images
        uses: docker/build-push-action@v4 
        with:
          context: ${{ matrix.component.path }}
          file: ${{ matrix.component.path }}/Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.component.name }}:latest

      - name: Generate SBOM for image
        uses: aquasecurity/trivy-action@master
        with:
          scan-ref: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.component.name }}:latest
          scan-type:  'image'
          format: 'cyclonedx'
          output: sbom-${{ matrix.component.name }}.json

      - name: Scan with trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-ref: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.component.name }}:latest
          format: 'json'
          scan-type: 'image'
          output: trivy-results-${{ matrix.component.name }}.json
          severity: 'CRITICAL,HIGH'
          exit-code: '0'
          ignore-unfixed: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-${{ matrix.component.name }}
          path: sbom-${{ matrix.component.name}}.json

      - name: Upload Trivy scan results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results-${{ matrix.component.name }}
          path: trivy-results-${{ matrix.component.name }}.json
