name: loanapp-project-ci
on:
 push:
    branches:
      - main
    pull_request:
      branches:
        - main

    permissions:
      contents: read
      packages: write


env:
  GO_VERSION: '1.21'

jobs:
  docker-build-push:
    name: Docker image build, sign and  push
    #needs: build-test-scan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component:
          - name: government-api
            path: './government_api/backend'
          - name: loanapp-validator
            path: './loan_validator_portal/backend'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: ${{ matrix.component.path }}
          file: ${{ matrix.component.path }}/Dockerfile
          push: false
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ matrix.component.name }}:v1
          cache-from: type=gha
          cache-to: type=gha,mode=max

      